apiVersion: v1
kind: Service
metadata:
  name: backend-deployment-service
  labels:
    app.kubernetes.io/name: backend-deployment-service
spec:
  selector:
    app.kubernetes.io/name: backend-deployment
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}