apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-deployment
  labels:
    app.kubernetes.io/name: backend-deployment

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: backend-deployment

  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend-deployment

    spec:
      containers:
      - name: k8s-test-backend
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: backend-configmap
        ports:
        - containerPort: {{ .Values.backend.port }}
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      imagePullSecrets:
        - name: us-east-1-ecr-registry