apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend-deployment
  labels:
    app.kubernetes.io/name: frontend-deployment

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend-deployment

  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend-deployment

    spec:
      containers:
      - name: k8s-test-frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.frontend.port }}
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      imagePullSecrets:
        - name: us-east-1-ecr-registry