apiVersion: v1
kind: Service
metadata:
  name: frontend-deployment-service
  labels:
    app.kubernetes.io/name: frontend-deployment-service
spec:
  selector:
    app.kubernetes.io/name: frontend-deployment
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}